name: Inspect Pull Requests

on:
  pull_request:
    branches: [main]

jobs:
  inspect:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      # - linting all packages that have a lint script
      # - building all packages that have a build script
      # - getting coverage for all packages that have a test:coverage script
      # - generating a bundlesize report for ui-components package
      # - running danger to check the results of the bundlesize report
      - run: |
          corepack enable
          yarn set version berry
          yarn install
          npx lerna run lint
          npx lerna run build
          npx lerna run test:coverage
          npx lerna run stats:pr --scope=@versini/ui-components
      - uses: mshick/add-pr-comment@v2
        with:
          token: ${{ secrets.NODE_CLI }}
          message: |
            **Hello**
            ğŸŒ
            !
